# Site settings
title: Tears in Rain
header-img: img/home-bg.png
email: helenkeomany@gmail.com
copyright_name: helenkeomany
description: > # this means to ignore newlines until "baseurl:"
  Or How I'd Rather Be A Replicant
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  helenkeomany
learn_profile: helenkeomany
email_username: helenkeomany@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
